Issue/600 video cover
doka-guide/y-doka.site pull request #601
Opened 2021-03-01 09:25 UTC by furtivite

- Перенастроил блок с картинками-обложками
    Тут, кажется, есть немного оверинжиниринга, могу упросить и сделать меньше уровней вложенности например так:
    ```njk
    cover:
        desktop:
        mobile:
        alt:
    ```
- Добавил возможность добавлять видео как обложку
- Добавил видео для статьи про focus

2021-03-01 11:07 UTC, solarrust commented
А какой кейс использования видео-обложки?

2021-03-01 11:26 UTC, furtivite commented
> А какой кейс использования видео-обложки?

У нас дизайнеры решили сделать анимированную обложку. Мы раньше решали, что гифки — это тяжело, а видео — это ок. Вот я и сделал анимированную обложку. Как-то так.

2021-03-01 12:21 UTC, pepelsbey requested changes

2021-03-01 12:21 UTC, pepelsbey commented on CONTRIBUTING.md
> +    poster: <!-- адрес постера = десктопная картинка -->
Здесь тоже бы примеры путей, как для картинки ниже

2021-03-01 12:21 UTC, pepelsbey commented on src/assets/styles/components/_article.scss
> +  &__cover-video {
Тут пока нет смысла для двух разных селекторов:

```suggestion
  &__cover-media {
```

Аналогично поменять в шаблоне.

2021-03-01 12:21 UTC, pepelsbey commented on src/layouts/post.njk
> +    <video autoplay muted loop width="900" height="537" src="{{ cover.video.src }}" src="{{ cover.video.poster }}" class="article__cover-video">
- Ставит класс первым, так проще читать разметку
- Правит ошибку в атрибуте

```suggestion
    <video class="article__cover-media" autoplay muted loop width="900" height="537" src="{{ cover.video.src }}" poster="{{ cover.video.poster }}">
```

2021-03-01 12:21 UTC, pepelsbey commented on src/layouts/post.njk
> +      Простите, но ваш браузер не поддерживает встроенные видео. Попробуйте скачать его <a href="{{ cover.video.src }}">по этой ссылке</a> и открыть его на своём устройстве.
Лучше не использовать «жмите сюда» или «по этой ссылке» для ссылок, стоит описывать что именно будет по ссылке.

```suggestion
      Простите, но ваш браузер не поддерживает встроенные видео. Попробуйте <a href="{{ cover.video.src }}">скачать видео</a> и открыть его на своём устройстве.
```

2021-03-01 12:21 UTC, pepelsbey commented on src/layouts/post.njk
> +      <img src="{{ cover.picture.desktop }}" width="900" height="537" class="article__cover-image" alt="{{ cover.picture.alt }}">
```suggestion
      <img class="article__cover-media" src="{{ cover.picture.desktop }}" width="900" height="537" alt="{{ cover.picture.alt }}">
```

2021-03-01 12:23 UTC, pepelsbey commented
Тут главный вопрос: а зачем нам иметь видео как обложку? Было бы круто какую-то мотивацию для решения, прежде чем само решение. На мой взгляд, автоплеить видео в браузере пользователя — это близко к преступлению. Ты читаешь текст, а рядом что-то пляшет и отвлекает.

2021-03-01 12:24 UTC, furtivite commented on src/layouts/post.njk
> +    <video autoplay muted loop width="900" height="537" src="{{ cover.video.src }}" src="{{ cover.video.poster }}" class="article__cover-video">
Блин, я опечатался, и вместо `poster` написал второй `src`

2021-03-01 12:26 UTC, furtivite commented on src/layouts/post.njk
> +      Простите, но ваш браузер не поддерживает встроенные видео. Попробуйте скачать его <a href="{{ cover.video.src }}">по этой ссылке</a> и открыть его на своём устройстве.
@pepelsbey, надо ли заодно исправить этот момент в статье про тег `<video>`?

2021-03-01 12:32 UTC, solarrust commented on src/layouts/post.njk
> +      Простите, но ваш браузер не поддерживает встроенные видео. Попробуйте скачать его <a href="{{ cover.video.src }}">по этой ссылке</a> и открыть его на своём устройстве.
Давайте разделим работы над платформой и ревью статей на разные потоки задач =)

2021-03-03 22:14 UTC, nlopin commented
> Тут главный вопрос: а зачем нам иметь видео как обложку? Было бы круто какую-то мотивацию для решения, прежде чем само решение. На мой взгляд, автоплеить видео в браузере пользователя — это близко к преступлению. Ты читаешь текст, а рядом что-то пляшет и отвлекает.

Согласен. Пошел [посмотреть](https://deploy-preview-601--y-doka.netlify.app/css/doka/focus/), там скорее микроанимация. Мне кажется такой формат норм, передает ментальную модель и запоминается.

То есть кажется можно, но очень нежно

2021-03-05 14:44 UTC, skorobaeus commented
Зашла написать, что видео не подстроено под мобильные (и не проигрывается на старых андроидах, но это, наверное, несущественно).

2021-03-08 06:24 UTC, nlopin commented
> Зашла написать, что видео не подстроено под мобильные (и не проигрывается на старых андроидах, но это, наверное, несущественно).

С мобилами вообще проблемки

2021-03-08 06:25 UTC, nlopin approved these changes

2021-06-14 08:41 UTC, closed without merging