Добавляет файл для редиректа на Netlify
doka-guide/y-doka.site pull request #726
Opened 2021-07-07 12:56 UTC by igsekor

С помощью Netlify можно настроить редиректы автоматически. Это описано в официальной документации. На первом этапе, пока мы на Netlify, предлагаю использовать именно такой подход.

Редирект решает задачу, которая описана в [issue](https://github.com/doka-guide/content/issues/1113). Как тольно будет готова платформа, можно слить в `master`.

2021-07-07 13:01 UTC, furtivite commented
Тут надо проверить новые ссылки на то, являются ли они битыми. Я займусь, и дополнительно сделать редиректы со спринтов на `/all/`. Замёржу сам.

2021-07-07 13:51 UTC, pepelsbey approved these changes
😍

2021-07-07 14:45 UTC, furtivite requested changes
Ждёт решения пиаров, и коммита с дополнительными ссылками.

2021-07-07 14:45 UTC, furtivite commented on _redirects
> +/css/doka/css-rule/                           https://doka.guide/css/css-rule
@solarrust как думаешь, стоит ли поменять адрес статьи с https://doka.guide/css/css-rule на https://doka.guide/css/rule, по аналогии с https://doka.guide/css/comments ?

2021-07-07 14:45 UTC, furtivite commented on _redirects
> +/js/long/testing-and-fake-objects/            https://doka.guide/js/testing-and-fake-objects/
Ждёт решения вот [этого пиара](https://github.com/doka-guide/content/pull/1112) в контенте

2021-07-07 14:45 UTC, furtivite commented on _redirects
> +/js/doka/promt/                               https://doka.guide/js/promt/
Тут не открывается страница на y-doka.site, надо проверить. На doka.guide всё хорошо.

2021-07-07 14:45 UTC, furtivite commented on _redirects
> +/js/tools/nodejs-tooling/                     https://doka.guide/tools/nodejs-tooling/
Ждёт решения вот [этого пиара](https://github.com/doka-guide/content/pull/1114) в контенте.

2021-07-07 15:00 UTC, furtivite approved these changes

2021-07-07 15:01 UTC, furtivite commented
Ждём дизайн? @pepelsbey @igsekor @nlopin @solarrust

2021-07-07 15:02 UTC, furtivite requested changes
Ждём переноса двух статей

2021-07-07 15:12 UTC, pepelsbey commented
Обсудим в пятницу, когда будем добавлять редиректы. Конвертну пока в черновик, чтобы не смёржили случайно.

2021-09-27 13:19 UTC, pepelsbey commented
Нужно смёржить за день до запуска и проверить, что всё работает.

2021-09-27 13:20 UTC, pepelsbey commented
@igsekor освежишь ПР? Кажется с 7 июля что-то менялось

2021-09-28 17:31 UTC, igsekor commented on _redirects
> +/js/long/testing-and-fake-objects/            https://doka.guide/js/testing-and-fake-objects/
Готово!

2021-09-28 17:31 UTC, igsekor commented on _redirects
> +/js/tools/nodejs-tooling/                     https://doka.guide/tools/nodejs-tooling/
Готово!

2021-09-28 22:29 UTC, pepelsbey approved these changes
Заряжаем ПР на ближайшие выходные перед запуском :)

2021-10-12 09:30 UTC, merged